---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    type: pv-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/storages"
  storageClassName: standard