---

- name: Pull requirement docker images before init
  shell: kubeadm config images pull
  changed_when: false

- name: Kubernetes promote master
  shell: 'kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ ip_controller[0] }}'
  args:
    creates: /etc/kubernetes/cluster_initialized.txt

- name: Kubernetes create initialize file
  file:
    path: /etc/kubernetes/cluster_initialized.txt
    state: touch

- name: Create config directory
  file:
    path: '/home/{{ ansible_user }}/.kube'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0755

- name: Copy kubernetes config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: '/home/{{ ansible_user }}/.kube/config'
    remote_src: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0600
